package fi.vm.sade.viestintapalvelu;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.VelocityEngine;
import org.odftoolkit.odfdom.converter.core.utils.ByteArrayOutputStream;
import org.w3c.tidy.Configuration;
import org.w3c.tidy.Tidy;
import org.xhtmlrenderer.pdf.ITextRenderer;

import com.lowagie.text.DocumentException;

public class AddressLabelBuilder {
	
	private VelocityEngine templateEngine = new VelocityEngine();
	
	public AddressLabelBuilder() {
		templateEngine.init();
	}
	
	public byte[] printAddressLabels(AddressLabelBatch input) throws DocumentException, IOException {
		if (isPDFTemplate(input.getTemplateName())) {
			return toPDF(toXHtml(input));
		} else {
			return evaluateTemplate(input);
		}
	}
	
	private boolean isPDFTemplate(String templateName) {
		return templateName != null && templateName.toUpperCase().endsWith(".HTML");
	}

	private byte[] toPDF(byte[] input) throws UnsupportedEncodingException, DocumentException {
    	ByteArrayOutputStream output = new ByteArrayOutputStream();
    	newITextRenderer(input).createPDF(output);
		return output.toByteArray();
	}

	private byte[] toXHtml(AddressLabelBatch input) throws IOException {
		return toXhtml(evaluateTemplate(input));
	}
	
	private byte[] evaluateTemplate(AddressLabelBatch input) throws FileNotFoundException, IOException {
		byte[] template = readTemplate(input.getTemplateName());
		return bindDataToTemplate(template, input.getAddressLabels());
	}

	private byte[] bindDataToTemplate(byte[] template, List<AddressLabel> labels) throws UnsupportedEncodingException {
		StringWriter writer = new StringWriter();
		templateEngine.evaluate(newContext(labels), writer, "LOG", new InputStreamReader(new ByteArrayInputStream(template)));
		return writer.toString().getBytes();
	}

	private byte[] toXhtml(byte[] document) {
		ByteArrayOutputStream out = new ByteArrayOutputStream();
		newTidy().parseDOM(new ByteArrayInputStream(document), out);
		return out.toByteArray();
	}

	private ITextRenderer newITextRenderer(byte[] input) {
		ITextRenderer renderer = new ITextRenderer();
        renderer.setDocumentFromString(new String(input), "/");
        renderer.layout();
		return renderer;
	}

	private Tidy newTidy() {
		Tidy tidy = new Tidy();
		tidy.setTidyMark(false);
		tidy.setDocType("omit");
		tidy.setXHTML(true);
		tidy.setCharEncoding(Configuration.UTF8);
		return tidy;
	}

	private VelocityContext newContext(List<AddressLabel> addressLabels) {
		VelocityContext context = new VelocityContext();
		context.put("labelList", addressLabels);
		return context;
	}

	private byte[] readTemplate(String templateName) throws FileNotFoundException, IOException {
		InputStream in = getClass().getResourceAsStream(templateName);
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		baos.write(in);
		return baos.toByteArray();
	}

	private void writeDocument(String name, byte[] document) {
		FileOutputStream fos = null;
		try {
			File file = new File("target/documents/" + name);
			file.getParentFile().mkdirs();
			fos = new FileOutputStream(file, false);
			fos.write(document, 0, document.length);
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (fos != null) {
				try {
					fos.close();
				} catch (IOException e) {
				}
			}
		}
	}

	public static void main(String[] args) throws Exception {
		List<AddressLabel> labels = new ArrayList<AddressLabel>();
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Venäjä"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Tanska"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Norja"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Ruotsi"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Meiju", "Aalto-Setälä", "Kauriintie 3 D 31", "00740", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Aarnio", "Lumi", "Tilkankatu 7b 24", "00300", "HELSINKI", "Finland"));
		labels.add(new AddressLabel("Maria", "Abbas-Hashimi", "Petter wetterin tie 6 c 46", "00810", "Helsinki", "Finland"));
		labels.add(new AddressLabel("Hodan", "Abdi", "Postirestante", "00840", "Helsinki", "Finland"));
		AddressLabelBatch batch = new AddressLabelBatch("/osoitetarrat.csv", labels);
		AddressLabelBuilder service = new AddressLabelBuilder();
		service.writeDocument("tarrat.csv", service.printAddressLabels(batch));
	}

}
